from collections import defaultdict
UNK_LABEL = "[UNK]"
UNK_IDX = 0
PADDING_LABEL = "[PAD]"
PADDING_IDX = 1

TRIGGER_ARG_MAP = defaultdict(set)
TRIGGER_ARG_MATRIX = None
TOKEN_MASK_TYPE = 'average'

VOCAB_START_IDX = 2
ONECHANCE = True
CUTOFF = 60
TRIGGER_ANCHOR_NUM = 1
ENTITY_ANCHOR_NUM = 6
VISIABLE = False

TRIGGER_O_LABEL = None
TRIGGER_PAD_LABEL = None
ENTITY_O_LABEL = None
ENTITY_PAD_LABEL = None
ROLE_O_LABEL = None
