from collections import defaultdict
UNK_LABEL = "<unk>"
UNK_IDX = 0
PADDING_LABEL = "<pad>"
PADDING_IDX = 1

TRIGGER_ARG_MAP = defaultdict(set)
TRIGGER_ARG_MATRIX = None
TOKEN_MASK_TYPE = 'average'

VOCAB_START_IDX = 2
ONECHANCE = True
CUTOFF = 45
TRIGGER_ANCHOR_NUM = 1
ENTITY_ANCHOR_NUM = 6
TRIGGER_GOLDEN_COMPENSATION = 12
ARGUMENT_GOLDEN_COMPENSATION = 27
VISIABLE = False

TRIGGER_O_LABEL = None
TRIGGER_PAD_LABEL = None
ENTITY_O_LABEL = None
ENTITY_PAD_LABEL = None
ROLE_O_LABEL = None
